version: '3.9'

services:
  kamasutraescort.api:
    image: shukharatovich/kamasutraescort
    container_name: kamasutraescort
    restart: always
    ports:
      - 3001:3001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.env:/opt/app/.env

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 ubuntu-container kamasutraescort
