name: Docker Image CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Build the Docker image
        run: |
          docker build -t kamasutraescort .
          export CR_PAT=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 
          echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
          docker tag kamasutraescort ghcr.io/shukharatovich-a/kamasutraescort
          docker push ghcr.io/shukharatovich-a/kamasutraescort
