name: Docker Image CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Build the Docker image
        run: |
          docker build -t kamasutraescort .
          docker login -u shukharatovich -p dckr_pat_s1OM4oX4oFosCNHLYrAqQnAGwZU
          docker tag kamasutraescort shukharatovich/kamasutraescort
          docker push shukharatovich/kamasutraescort
